config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "projects#index"
  get "/index_projects/" =>'projects#index'
  post 'checkout/create' => 'checkout#create', as: "checkout_create"
  resources :webhooks, only: [:create]
  resources :projects do
   resources :tasks
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user
  validates :name, presence: true

  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end

  def status
    return 'not-started' if tasks.none?

    if tasks.all? { |task| task.complete? }
      'complete'
    elsif tasks.any? { |task| task.in_progress? || task.complete? }
      'in-progress'
    else
      'not-started'
    end
  end

  def percent_complete
    return 0 if tasks.none?
    ((total_complete.to_f / total_tasks) * 100).round
  end

  def total_complete
    tasks.select { |task| task.complete? }.count
  end

  def total_tasks
    tasks.count
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  validates :name, presence: true 

  validates :status, inclusion: { in: ['not-started', 'in-progress', 'complete'] }

  STATUS_OPTIONS = [
    ['Not started', 'not-started'],
    ['In progress', 'in-progress'],
    ['Complete', 'complete']
  ]

  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end

  def complete?
    status == 'complete'
  end

  def in_progress?
    status == 'in-progress'
  end

  def not_started?
    status == 'not-started'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/checkout_controller.rb
def create
    @session = Stripe::Checkout::Session.create({
      success_url: root_url,
      cancel_url: manage_posts_url,
      payment_method_types: ['card'],
      line_items: [{
          name: "Roommate Posting",
          amount: 2000,
          currency: "inr",
          quantity: 1
      }],
      mode: 'payment',
      metadata: {project_id: params[:project_id]},
      customer_email: current_user.email,
      success_url: manage_posts_url,
      cancel_url: manage_posts_url
    })
  
    respond_to do |format|
      format.turbo_stream
    end
  end
  

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @projects = current_user.projects.where(:is_paid => true)
  end

  def show
    @project = Project.find(params[:id])
    @task = Task.new(project: @project)
    @tasks = @project.tasks.order(:created_at)
    render 'show'
  end

  def new
    @project = current_user.projects.build
  end

  def edit
  end
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_path, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.turbo_stream { render :form_update, status: :unprocessable_entity }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.turbo_stream { render :form_update, status: :unprocessable_entity }
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description)
    end
  end 

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = @project.tasks
  end

  def show
  end


  def new
    @task = @project.tasks.build
  end

  def edit
  end

  def create
    @task = @project.tasks.build(task_params)

    if @task.save
      redirect_to(@task.project)
    else
      render action: 'new'
    end
  end

  def update
    if @task.update(task_params)
      redirect_to(@task.project)
    else

      format.turbo_stream { render :form_update, status: :unprocessable_entity }
      render action: 'edit'
    end
  end

  def destroy
    @task.destroy

    redirect_to @project
  end

  private
    def set_project
      @project = current_user.projects.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :description, :status, :project_id)
    end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
    skip_before_action :verify_authenticity_token
  
    def create
      payload = request.body.read
      sig_header = request.env['HTTP_STRIPE_SIGNATURE']
      event = nil
  
      begin
      event = Stripe::Webhook.construct_event(
        payload, sig_header, Rails.application.credentials[:stripe][:webhook]
      )
      rescue JSON::ParserError => e
        status 400
      return
      rescue Stripe::SignatureVerificationError => e
        # Invalid signature
        puts "Signature error"
        p e
        return
      end
  
      # Handle the event
      case event.type
      when 'checkout.session.completed'
        session = event.data.object
        project = Project.find_by(id: session.metadata.project_id)
        project.is_paid = true
        project.save!
      end
  
      render json: { message: 'success' }
    end
  end 
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/checkout/create.turbo_stream.erb
var stripe = Stripe("<%= Rails.application.credentials[:stripe][:public] %>")

stripe.redirectToCheckout({
    sessionId: '<%= @session.id %>'
}).then(function (result) {
    console.log(result.error_message)
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeePortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
 <body class='bg-light'>
    <div class="container pt-5 pb-5">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="card">
       <div class="card-body">
        <%= yield %>
        <%= turbo_frame_tag "remote_modal", target: "_top" %>
      </div>
    </div>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: @project, class: "form") do |form| %>

  <div class="form-group">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>



  <div class="form-group">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= project.user_id %>
  </p>

</div>

app/views/projects/edit.html.erb
<%= render "shared/remote_modal", title: "Edit this Project" do %>

<%= render "form", project: @project %>
<%= render 'shared/errors', obj: @project %>
<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to project", project_path(@project) %>
</div>
<% end %>

app/views/projects/form_update.turbo_stream.erb
<%= turbo_stream.update "remote_modal_body" do %>
    <%= render 'shared/errors', obj: @project %>
    <%= render "form", project: @project %>
  <% end %>

app/views/projects/index.html.erb
<div class="card">
  <div class="card-body">
    <div class="d-flex justify-content-between align-items-center mb-4"><br/>
      <h2 class="card-title mb-0"><div class="shadow-lg p-3 mb-5 bg-body rounded">Projects</div></h2>
      <div>
        <%= link_to 'New Project', new_project_path, data: { turbo_frame: "remote_modal" }, class: 'btn btn-primary mr-2' %>
        <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-secondary' %>
      </div>
    </div>
    <% @current_user.projects.each do |project| %>
      <%= link_to project, class: 'text-decoration-none' do %>
        <div class="card project-card mb-3">
          <div class="card-body">
            <div class="mb-3">
              <span class="badge badge-<%= project.badge_color %>">
                <%= project.status %>
              </span>
              <span class='text-secondary'>
                <small>
                  <%= project.percent_complete %>% complete
                  (<%= project.total_complete %>/<%= project.total_tasks %> tasks)
                </small>
              </span>
            </div>
            <h5 class='card-title text-dark'><b><%= project.name %></b></h5>
            <p class='text-secondary'><%= project.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<%= render "shared/remote_modal", title: "New Project" do %>


<%= render "form", project: @project %>
<%= render 'shared/errors', obj: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>
<% end %>

app/views/projects/show.html.erb
<%= link_to 'Back', projects_path, class: 'btn btn-secondary mb-3' %>

<div class="card">
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between mb-4'>
    <span class="h3"><b><%= @project.name %></b></span>
      <div>
      <% if current_user %>
        <%= link_to 'Edit', edit_project_path(@project), data: { turbo_frame: "remote_modal" }, class: 'btn btn-warning mr-2' %>
        <%= link_to 'Destroy', @project, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger"  %>
      <% end %>
      </div>
    </h2>
    <p><%= @project.description %></p>

    <div class="mb-4">
      <h6 class="mb-3">Add task</h6>
      <%= form_for([@task.project, @task]) do |f| %>
        <% if @task.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h4><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h4>

            <ul>
            <% @task.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <%= f.hidden_field :status, value: 'not-started' %>
        <div class="input-group">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Enter task name...' %>
          <div class="input-group-append">
            <%= f.submit class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>

    <h4 class="mb-3">Tasks</h4>
    <% @project.tasks.each do |task| %>
      <% if task.persisted? %>
        <div class="card mb-3">
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
              <span class="badge badge-<%= task.badge_color %>"><%= task.status %></span>
            <div>
            <% if current_user %>
              <%= link_to 'Edit', edit_project_task_path(task.project, task), data: { turbo_frame: "remote_modal" }, class: 'btn btn-warning mr-2' %>
              <%= link_to 'Destroy', [task.project, task], data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger"  %>
            <% end %>
            </div>
        
            </div>
            <h5 class='card-title mb-2'>
              <span><%= link_to task.name, project_task_path(task.project, task), data: { turbo_frame: "remote_modal" } %></span>
            </h5>
            <p><%= task.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
    

  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
  <h2><%= pluralize(obj.errors.count, "error") %> prohibited from being saved:</h2>

  <ul>
    <% obj.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_remote_modal.html.erb
<%= turbo_frame_tag "remote_modal" do %>

    <div class="modal fade" id="shareRecipeModal" tabindex="-1" aria-labelledby="newItemRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content" id="modal_content">
                <div class="modal-header">
                    <h4 class="modal-title" id="newItemRemoteModalLabel"><%= title %></h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body remote_modal_body" id="remote_modal_body">
                    <%= yield %>
                </div>
            </div>
        </div>
    </div>

<% end %>

app/views/tasks/_form.html.erb
<%= form_for([@task.project, @task], html: {class: "needs-validation", novalidate: true}) do |f| %>

  <div class="form-group">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-control", required: true %>
    <div class="invalid-feedback">
      Please enter a task name.
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :status, class: "form-label" %>
    <%= f.select :status, Task::STATUS_OPTIONS, {}, { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.submit "Save task", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render "shared/remote_modal", title: "New Project" do %>
<%= render 'shared/errors', obj: @task %>

<%= render 'form',task: @task %>

<%= link_to 'Show', [@task.project, @task] %> |
<%= link_to 'Back', project_path(@project) %>
<% end %>

app/views/tasks/form.turbo_stream.erb
<%= turbo_stream.update "remote_modal_body" do %>
    <%= render 'shared/errors', obj: @task %>
    <%= render "form", task: @task %>
  <% end %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td><%= task.project %></td>
    <td><%= link_to 'Show', [task.project, task] %></td>
    <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
    <td><%= link_to 'Destroy', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_project_task_path(params[:project_id]) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>
<%= render 'shared/errors', obj: @task %>
<%= link_to 'Back', project_tasks_path(@task.project) %>

app/views/tasks/show.html.erb
<%= render "shared/remote_modal", title: "Task Details" do %>
<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Project:</b>
  <%= @task.project.name %>
</p>


<%= link_to 'Back', project_path(@project) %>
<% end %>